name: WildAware CI/CD

on:
  push:
    branches: [ prod, pre-prod ]
  pull_request:
    branches: [ prod, pre-prod ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Lint with flake8
        run: |
          pip install flake8
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics --exit-zero

      - name: Safety check dependencies
        run: |
          pip install safety
          safety check --ignore=71671,71672,64437,64436,67136

  build:
    needs: test
    runs-on: ubuntu-latest
    if: github.event_name == 'push' || github.event_name == 'pull_request'
    steps:
      - uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile  # Assurez-vous que ce fichier existe
          push: false
          tags: wildaware:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max